#!/bin/bash
# installs CCGlab externals, to go with git ccglab repo.   -cem bozsahin
#  also sets PATH and lisp execs so that ccglab is available from anywhere
ccglabdir=`pwd`
locallisp=
echo 'CCGlab external resources install and path set up'
echo '================================================='
echo 'Looking for SBCL or CCL Common Lisp in your machine'
echo 'You can execute "which sbcl" or "which ccl" etc in another terminal to find out the full path'
if [ -f "/usr/local/bin/sbcl" ] || [ -f "/usr/bin/sbcl" ] || [ -f "/usr/local/bin/ccl" ] || [ -f "/usr/bin/ccl" ]; then
  echo 'CCGlab install: An installed ANSI Common Lisp is found'
  echo '? If you do not want to use an existing Lisp reply NONE'
  read -p '? What is the full path of your preferred Lisp executable? ' locallisp
else
  unset locallisp
fi
if [ -vlocallisp ] && [ -f "$locallisp" ]; then 
  echo 'CCGlab install: got it.'
else
  echo '! CCGlab install: There is no such local Lisp.'
  echo '! Set the CCGLAB_LISP variable in .bashrc to your binary if I cannot install SBCL'
  unset locallisp
fi
# check to see if lalr has been installed before
if [ ! -vLALR_HOME ]; then
  read -p $'CCGlab install: lalrparser.lisp package is external to CCGlab but required.\n   Where do you want to install it? ' lalr
  if [ -d "$lalr" ] && [ -w "$lalr" ]; then
    cd $lalr
    wget -v --no-check-certificate --backups=3 http://web.science.mq.edu.au/~mjohnson/code/lalrparser.lisp
    lalr=`pwd`
  else
    echo '! $lalr: No such writable directory. Re-run this script to finish the partial install.'
    exit -1
  fi
else
  lalr=$LALR_HOME
fi
# check to see if a Lisp for ccglab has been installed before
if [ ! -vlocallisp ]; then
  packager=:
  if [ -f "/usr/local/bin/brew" ] || [ -f "/sw/bin/brew" ] || [ -f "/sw/local/bin/brew" ]; then
    	packager=brew
  fi
  if [ -f "/usr/bin/apt-get" ] || [ -f "/usr/local/bin/apt-get" ]; then
	packager=apt-get   # overrides brew if you have them both
  fi
  if test $packager != ':' ; then
	echo 'CCGLAB install: you have an installer for standard packages'
	echo 'I can install SBCL and rlwrap from standard repositories'
	read -p '? Do you want to install SBCL [y/n]? ' auxinstall
	if test $auxinstall = 'y' ; then
		echo '! CCGlab install: WARNING: you need sudo access now'
		sudo $packager install sbcl
		locallisp=/usr/bin/sbcl
	fi
	if [ -f "/usr/local/bin/rlwrap" ] || [ -f "/usr/bin/rlwrap" ] || [ -f "/sw/bin/rlwrap" ] || [ -f "/sw/local/bin/rlwrap" ]; then
		echo 'Using rlwrap'
	else 
           read -p '? Do you want to install rlwrap [y/n]? ' auxinstall
	   if test $auxinstall = 'y' ; then
		echo '! CCGlab install: WARNING: you need sudo access now'
		sudo $packager install rlwrap
	   fi
        fi
  else
	echo '! apt-get or brew not found. I leave Common Lisp and rlwrap handling to you.'
  fi
else
  echo "Using the Lisp at $locallisp for CCGlab"
fi
# check to see if there is already a ccglab
if [ -vCCGLAB_HOME ]; then
  echo 'You have a CCGlab system installed.'
  echo 'If it is not a git repo, then it is legacy CCGlab code'
  echo '! Consider a new location if it is not a git repo'
  read -p "? Do you want me to stay at CCGLAB_HOME = $CCGLAB_HOME [y/n] ? " reinstall
  if test $reinstall = 'y' ; then
    echo 'Using existing system. Best to do a "git pull" there to refresh.'
  else
    read -p '? What is the new location for CCGlab home ? ' newloc
    if [ -d "$newloc" ] && [ -w "$newloc" ]; then
      ccglabdir="$newloc"
      echo "OK. Make sure $ccglabdir has a copy of ccglab repo since install no longer downloads it but uses git"
    else
      echo "! $newloc: Not a writable directory. Re-run this script to finish the partial install"
      exit -1
    fi
  fi
fi
printf '%s\n' '# stuff added by CCGlab installer' >> ~/.bashrc
if [ -f "/usr/local/bin/rlwrap" ] || [ -f "/usr/bin/rlwrap" ] || [ -f "/sw/bin/rlwrap" ] || [ -f "/sw/local/bin/rlwrap" ]; then
  printf '%s\n' 'export RLWRAP=rlwrap' >> ~/.bashrc
  echo 'CCGlab install: you have got rlwrap. Using it for ccglab'
else
  printf '%s\n' 'export RLWRAP=' >> ~/.bashrc
  echo '! CCGlab install: rlwrap not found. If installed later, change the RLWRAP variable in .bashrc'
fi
printf '%s\n%s\n%s\n%s\n' "export CCGLAB_HOME=$ccglabdir" "export CCGLAB_LISP=$locallisp" "export LALR_HOME=$lalr" "export PATH=\$CCGLAB_HOME/bin:\$PATH" >> ~/.bashrc
printf '%s\n' '# end of stuff added by CCGlab installer' >> ~/.bashrc
printf '%s\n' '# stuff added by CCGlab installer' >> ~/.bash_profile
printf '%s\n' 'if [ -f ~/.bashrc ]; then source ~/.bashrc; fi' >> ~/.bash_profile
if [ -vreinstall ]; then
  echo '! You have re-installed ccglab. Make sure its home is a git repo'
fi
echo '! Dont forget to look at git repo once in a while for updates: just do "git pull"'
echo 'CCGlab install: completed.'
echo 'To run, first open a fresh terminal, or logout and login. Then do'
echo 'ccglab'
echo '================================================='
